### ISSUE TITLE
[FRONTEND] - Create cards and lateral menu items

### ISSUE THREAD

**Issue by fsdevWebmaster** [fsdevWebmaster/proyecto-final#136]
Filter must work for every role

**Comment by FranJimenezQ** [comment]
Menu:
- Usuarios:
   - Lista Usuarios
   - Crear usuario
- Contenedores:
    - Lista Contenedores
    - Crear Contenedor
- Estaciones: (aqui iria un item por estacion)
- Mi Perfil
